# Generated by Django 2.2.3 on 2019-08-04 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
