# Generated by Django 2.2.3 on 2019-08-15 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20190815_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
